package au.edu.unsw.soacourse.onboardingservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2017-03-16T16:41:52.450+11:00
 * Generated source version: 3.0.4
 * 
 */
@WebServiceClient(name = "OnboadrdingValidationService", 
                  wsdlLocation = "file:/Users/linus/cs9322/workspace/onboarding-validation-service/src/main/resources/wsdl/OnboadrdingValidationService.wsdl",
                  targetNamespace = "http://onboardingservice.soacourse.unsw.edu.au") 
public class OnboadrdingValidationService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://onboardingservice.soacourse.unsw.edu.au", "OnboadrdingValidationService");
    public final static QName OnboadrdingValidationServiceSOAP = new QName("http://onboardingservice.soacourse.unsw.edu.au", "OnboadrdingValidationServiceSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/linus/cs9322/workspace/onboarding-validation-service/src/main/resources/wsdl/OnboadrdingValidationService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(OnboadrdingValidationService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/Users/linus/cs9322/workspace/onboarding-validation-service/src/main/resources/wsdl/OnboadrdingValidationService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public OnboadrdingValidationService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public OnboadrdingValidationService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OnboadrdingValidationService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public OnboadrdingValidationService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public OnboadrdingValidationService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public OnboadrdingValidationService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns OnboadrdingValidationService
     */
    @WebEndpoint(name = "OnboadrdingValidationServiceSOAP")
    public OnboadrdingValidationService getOnboadrdingValidationServiceSOAP() {
        return super.getPort(OnboadrdingValidationServiceSOAP, OnboadrdingValidationService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OnboadrdingValidationService
     */
    @WebEndpoint(name = "OnboadrdingValidationServiceSOAP")
    public OnboadrdingValidationService getOnboadrdingValidationServiceSOAP(WebServiceFeature... features) {
        return super.getPort(OnboadrdingValidationServiceSOAP, OnboadrdingValidationService.class, features);
    }

}
