package au.edu.unsw.soacourse.onboardingservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2017-03-16T16:41:52.430+11:00
 * Generated source version: 3.0.4
 * 
 */
@WebService(targetNamespace = "http://onboardingservice.soacourse.unsw.edu.au", name = "OnboadrdingValidationService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface OnboadrdingValidationService {

    @WebMethod(operationName = "ValidateAddress", action = "http://onboardingservice.soacourse.unsw.edu.au/ValidateAddress")
    @WebResult(name = "ValidateAddressResponse", targetNamespace = "http://onboardingservice.soacourse.unsw.edu.au", partName = "parameters")
    public ValidateAddressResponse validateAddress(
        @WebParam(partName = "parameters", name = "ValidateAddressRequest", targetNamespace = "http://onboardingservice.soacourse.unsw.edu.au")
        ValidateAddressRequest parameters
    ) throws ValidateAddressFaultMsg;

    @WebMethod(operationName = "ValidateDriverLicense", action = "http://onboardingservice.soacourse.unsw.edu.au/ValidateDriverLicense")
    @WebResult(name = "ValidateDriverLicenseResponse", targetNamespace = "http://onboardingservice.soacourse.unsw.edu.au", partName = "parameters")
    public ValidateDriverLicenseResponse validateDriverLicense(
        @WebParam(partName = "parameters", name = "ValidateDriverLicenseRequest", targetNamespace = "http://onboardingservice.soacourse.unsw.edu.au")
        ValidateDriverLicenseRequest parameters
    ) throws ValidateDriverLicenseFaultMsg;
}
